In [1]:
import pandas as pd
headers = ["symboling", "normalized-losses", "make", "fuel-type", "aspiration", "num-of-doors", "body-style", "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight", "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price"]
data = pd.read_csv(r'C:\Users\Aryan Chollera\Downloads\data_set.data')
data.columns = headers
data

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            1                 ?  alfa-romero       gas        std   
2            2               164         audi       gas        std   
3            2               164         audi       gas        std   
4            2                 ?         audi       gas        std   
..         ...               ...          ...       ...        ...   
198         -1                95        volvo       gas        std   
199         -1                95        volvo       gas      turbo   
200         -1                95        volvo       gas        std   
201         -1                95        volvo    diesel      turbo   
202         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two    hatchback          rwd           front        94.5  ...   
2           four        sedan          fwd           front        99.8  ...   
3           four        sedan          4wd           front        99.4  ...   
4            two        sedan          fwd           front        99.8  ...   
..           ...          ...          ...             ...         ...  ...   
198         four        sedan          rwd           front       109.1  ...   
199         four        sedan          rwd           front       109.1  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            152         mpfi  2.68    3.47               9.0        154   
2            109         mpfi  3.19    3.40              10.0        102   
3            136         mpfi  3.19    3.40               8.0        115   
4            136         mpfi  3.19    3.40               8.5        110   
..           ...          ...   ...     ...               ...        ...   
198          141         mpfi  3.78    3.15               9.5        114   
199          141         mpfi  3.78    3.15               8.7        160   
200          173         mpfi  3.58    2.87               8.8        134   
201          145          idi  3.01    3.40              23.0        106   
202          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  16500  
1        5000       19          26  16500  
2        5500       24          30  13950  
3        5500       18          22  17450  
4        5500       19          25  15250  
..        ...      ...         ...    ...  
198      5400       23          28  16845  
199      5300       19          25  19045  
200      5500       18          23  21485  
201      4800       26          27  22470  
202      5400       19          25  22625  

[203 rows x 26 columns]

In [2]:
import numpy as np
data = np.array([data])
data = data.reshape(203, 26)
temp = data[:, 1]
sum = 0
count = 0
for i in range(203):
    if temp[i]!='?':
        temp[i] = int(temp[i])
        sum = sum + temp[i]
        count = count+1
avg = sum/count
for i in range(203):
    if temp[i] == '?':
        temp[i]=avg
data[:, 1] = temp
temp = data[:, 18]
sum = 0
count = 0
for i in range(203):
    if temp[i]!='?':
        temp[i] = float(temp[i])
        sum = sum + temp[i]
        count = count+1
avg = sum/count
for i in range(203):
    if temp[i] == '?':
        temp[i]=avg
data[:, 18] = temp
temp = data[:, 19]
sum = 0
count = 0
for i in range(203):
    if temp[i]!='?':
        temp[i] = float(temp[i])
        sum = sum + temp[i]
        count = count+1
avg = sum/count
for i in range(203):
    if temp[i] == '?':
        temp[i]=avg
data[:, 19] = temp
temp = data[:, 21]
sum = 0
count = 0
for i in range(203):
    if temp[i]!='?':
        temp[i] = float(temp[i])
        sum = sum + temp[i]
        count = count+1
avg = sum/count
for i in range(203):
    if temp[i] == '?':
        temp[i]=avg
data[:, 21] = temp
temp = data[:, 22]
sum = 0
count = 0
for i in range(203):
    if temp[i]!='?':
        temp[i] = float(temp[i])
        sum = sum + temp[i]
        count = count+1
avg = sum/count
for i in range(203):
    if temp[i] == '?':
        temp[i]=avg
data[:, 22] = temp
temp = data[:, 25]
sum = 0
count = 0
for i in range(203):
    if temp[i]!='?':
        temp[i] = int(temp[i])
        sum = sum + temp[i]
        count = count+1
avg = sum/count
for i in range(203):
    if temp[i] == '?':
        temp[i]=avg
data[:, 25] = temp
print(data)

[[3 122.0 'alfa-romero' ... 21 27 16500]
 [1 122.0 'alfa-romero' ... 19 26 16500]
 [2 164 'audi' ... 24 30 13950]
 ...
 [-1 95 'volvo' ... 18 23 21485]
 [-1 95 'volvo' ... 26 27 22470]
 [-1 95 'volvo' ... 19 25 22625]]


In [3]:
temp = data[:, 0]
temp, aa = pd.factorize(temp)
data[:, 0] = temp
temp = data[:, 2]
temp, aa = pd.factorize(temp)
data[:, 2] = temp
temp = data[:, 3]
temp, aa = pd.factorize(temp)
data[:, 3] = temp
temp = data[:, 4]
temp, aa = pd.factorize(temp)
data[:, 4] = temp
temp = data[:, 5]
temp, aa = pd.factorize(temp)
data[:, 5] = temp
temp = data[:, 6]
temp, aa = pd.factorize(temp)
data[:, 6] = temp
temp = data[:, 7]
temp, aa = pd.factorize(temp)
data[:, 7] = temp
temp = data[:, 8]
temp, aa = pd.factorize(temp)
data[:, 8] = temp
temp = data[:, 14]
temp, aa = pd.factorize(temp)
data[:, 14] = temp
temp = data[:, 15]
temp, aa = pd.factorize(temp)
data[:, 15] = temp
temp = data[:, 17]
temp, aa = pd.factorize(temp)
data[:, 17] = temp
print(data)

[[0 122.0 0 ... 21 27 16500]
 [1 122.0 0 ... 19 26 16500]
 [2 164 1 ... 24 30 13950]
 ...
 [4 95 21 ... 18 23 21485]
 [4 95 21 ... 26 27 22470]
 [4 95 21 ... 19 25 22625]]


In [4]:
data = pd.DataFrame(data)
data

0    1   2  3  4  5  6  7  8      9   ...   16 17    18    19   20   21  \
0    0  122   0  0  0  0  0  0  0   88.6  ...  130  0  3.47  2.68    9  111   
1    1  122   0  0  0  0  1  0  0   94.5  ...  152  0  2.68  3.47    9  154   
2    2  164   1  0  0  1  2  1  0   99.8  ...  109  0  3.19   3.4   10  102   
3    2  164   1  0  0  1  2  2  0   99.4  ...  136  0  3.19   3.4    8  115   
4    2  122   1  0  0  0  2  1  0   99.8  ...  136  0  3.19   3.4  8.5  110   
..  ..  ...  .. .. .. .. .. .. ..    ...  ...  ... ..   ...   ...  ...  ...   
198  4   95  21  0  0  1  2  0  0  109.1  ...  141  0  3.78  3.15  9.5  114   
199  4   95  21  0  1  1  2  0  0  109.1  ...  141  0  3.78  3.15  8.7  160   
200  4   95  21  0  0  1  2  0  0  109.1  ...  173  0  3.58  2.87  8.8  134   
201  4   95  21  1  1  1  2  0  0  109.1  ...  145  6  3.01   3.4   23  106   
202  4   95  21  0  1  1  2  0  0  109.1  ...  141  0  3.78  3.15  9.5  114   

       22  23  24     25  
0    5000  21  27  16500  
1    5000  19  26  16500  
2    5500  24  30  13950  
3    5500  18  22  17450  
4    5500  19  25  15250  
..    ...  ..  ..    ...  
198  5400  23  28  16845  
199  5300  19  25  19045  
200  5500  18  23  21485  
201  4800  26  27  22470  
202  5400  19  25  22625  

[203 rows x 26 columns]

In [5]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
data = np.array([data])
data = data.reshape(203, 26)
data = data.astype(np.float)
x = data[:, 1:26]
y = data[:, 0]
sclr = StandardScaler()
x = sclr.fit_transform(x)
x = x.reshape(203, 25)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [7]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(12, input_shape=(X_train.shape[1], ), activation='relu'))
model.add(Dense(6, activation='sigmoid'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics='accuracy')
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=51, epochs=1500)

Epoch 1/1500
4/4 [==============================] - 1s 69ms/step - loss: 1.8830 - accuracy: 0.2284 - val_loss: 1.9002 - val_accuracy: 0.2927
Epoch 2/1500
4/4 [==============================] - 0s 11ms/step - loss: 1.8402 - accuracy: 0.2593 - val_loss: 1.8729 - val_accuracy: 0.2927
Epoch 3/1500
4/4 [==============================] - 0s 14ms/step - loss: 1.7998 - accuracy: 0.2593 - val_loss: 1.8458 - val_accuracy: 0.2927
Epoch 4/1500
4/4 [==============================] - 0s 13ms/step - loss: 1.7645 - accuracy: 0.2901 - val_loss: 1.8196 - val_accuracy: 0.3171
Epoch 5/1500
4/4 [==============================] - 0s 13ms/step - loss: 1.7303 - accuracy: 0.3025 - val_loss: 1.7960 - val_accuracy: 0.3415
Epoch 6/1500
4/4 [==============================] - 0s 12ms/step - loss: 1.6991 - accuracy: 0.3148 - val_loss: 1.7738 - val_accuracy: 0.3415
Epoch 7/1500
4/4 [==============================] - 0s 13ms/step - loss: 1.6673 - accuracy: 0.3395 - val_loss: 1.7536 - val_accuracy: 0.3659
Epoch 8/1500


In [8]:
pred = model.predict(X_test)
classes=np.argmax(pred,axis=1)
print(classes)

[3 3 3 1 4 1 3 0 4 4 4 2 2 2 0 2 1 0 0 3 4 1 1 2 0 3 3 4 0 0 1 1 0 4 2 3 3
 2 1 1 0]


In [9]:
model.add(Dense(12, input_shape=(X_train.shape[1], ), activation='relu', kernel_regularizer=tf.keras.regularizers.l1(0.01)))
model.add(Dense(6, activation='sigmoid'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics='accuracy')
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=51, epochs=1500)

Epoch 1/1500
4/4 [==============================] - 1s 65ms/step - loss: 2.0582 - accuracy: 0.3765 - val_loss: 1.9603 - val_accuracy: 0.4146
Epoch 2/1500
4/4 [==============================] - 0s 13ms/step - loss: 2.0366 - accuracy: 0.3951 - val_loss: 1.9480 - val_accuracy: 0.4146
Epoch 3/1500
4/4 [==============================] - 0s 13ms/step - loss: 2.0158 - accuracy: 0.4074 - val_loss: 1.9365 - val_accuracy: 0.4146
Epoch 4/1500
4/4 [==============================] - 0s 11ms/step - loss: 1.9959 - accuracy: 0.4136 - val_loss: 1.9260 - val_accuracy: 0.4390
Epoch 5/1500
4/4 [==============================] - 0s 21ms/step - loss: 1.9778 - accuracy: 0.4444 - val_loss: 1.9161 - val_accuracy: 0.4390
Epoch 6/1500
4/4 [==============================] - 0s 19ms/step - loss: 1.9596 - accuracy: 0.4506 - val_loss: 1.9062 - val_accuracy: 0.4390
Epoch 7/1500
4/4 [==============================] - 0s 13ms/step - loss: 1.9426 - accuracy: 0.4506 - val_loss: 1.8967 - val_accuracy: 0.4390
Epoch 8/1500


In [10]:
pred1 = model.predict(X_test)
classes1=np.argmax(pred1,axis=1)
print(classes1)

[1 3 3 0 4 1 3 0 4 4 4 2 2 1 0 3 1 0 0 3 4 1 1 2 0 1 4 4 0 2 3 4 2 4 2 3 3
 2 1 1 0]
